name: Java Maven CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Compile Project
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn test

      - name: Package WAR
        run: mvn package

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=Train-Ticket-Booking \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrainBook-WAR
          path: target/*.war